### ISSUE TITLE
Update to Surefire 3.2.1 fails tests with timeout related exceptions

### ISSUE THREAD

**Issue by javiertuya** [javiertuya/samples-test-java#126]
Executing in CI the update #124 fails IT tests (repeatable):

```
[INFO] Running giis.demo.descuento.it.ITDescuento
Error:  Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 19.08 s <<< FAILURE! -- in giis.demo.descuento.it.ITDescuento
Error:  giis.demo.descuento.it.ITDescuento.testDescuentoScenario -- Time elapsed: 18.56 s <<< ERROR!
org.assertj.swing.exception.WaitTimedOutError: 
Timed out waiting for component to be found using matcher org.assertj.swing.core.NameMatcher[name='Descuento', type=java.awt.Frame, requireShowing=true]
Unable to find component using matcher org.assertj.swing.core.NameMatcher[name='Descuento', type=java.awt.Frame, requireShowing=true].
```

**Comment by javiertuya** [comment]
Running verify in local gives that all IT failures are related to assertj.swing

```
[INFO] Running giis.demo.descuento.it.ITDescuento
nov 03, 2023 8:29:04 A. M. org.assertj.swing.monitor.ProtectingTimerTask handleException
ADVERTENCIA: Exception thrown by a TimerTask
java.lang.reflect.InaccessibleObjectException: Unable to make field int java.util.TimerTask.state accessible: module java.base does not "opens java.util" to unnamed module @1b083826
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
...
´´´

It seems that the new failsafe version is now using modules. When assertj.swing tries to access to a private field, the exception is raised

The solution is to open the module adding `--add-opens java.base/java.util=ALL-UNNAMED` to the surefire arg line
